import React, { ReactComponentElement, ReactElement, ReactNode } from 'react';
import {
  AreaChartOutlined,
  PieChartOutlined,
  BarChartOutlined,
  DotChartOutlined,
  LineChartOutlined,
  RadarChartOutlined,
  HeatMapOutlined,
  FundOutlined,
  SlidersOutlined,
  AndroidOutlined,
  AppleOutlined,
  WindowsOutlined,
  ChromeOutlined,
  GithubOutlined,
  CodeSandboxOutlined,
  AccountBookOutlined,
  ApartmentOutlined,
  ApiOutlined,
  AppstoreOutlined,
  AuditOutlined,
  BankOutlined,
  BarsOutlined,
  BookOutlined,
  BugOutlined,
  BuildOutlined,
  CalendarOutlined,
  CiOutlined,
  ClearOutlined,
  CloudDownloadOutlined,
  CloudOutlined,
  ClusterOutlined,
  CodeOutlined,
  CommentOutlined,
  CompassOutlined,
  ConsoleSqlOutlined,
  ContactsOutlined,
  ControlOutlined,
  CreditCardOutlined,
  CrownOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  DeploymentUnitOutlined,
  DesktopOutlined,
  DownloadOutlined,
  EnvironmentOutlined,
  ExperimentOutlined,
  FireOutlined,
  FlagOutlined,
  GiftOutlined,
  GlobalOutlined,
  HistoryOutlined,
  HomeOutlined,
  IdcardOutlined,
  InboxOutlined,
  InsuranceOutlined,
  KeyOutlined,
  MailOutlined,
  MenuOutlined,
  MedicineBoxOutlined,
  MoneyCollectOutlined,
  PictureOutlined,
  ProfileOutlined,
  QrcodeOutlined,
  ReadOutlined,
  RobotOutlined,
  SafetyOutlined,
  ScheduleOutlined,
  SearchOutlined,
  SendOutlined,
  SettingOutlined,
  ShareAltOutlined,
  ShopOutlined,
  ShoppingCartOutlined,
  ShoppingOutlined,
  SkinOutlined,
  SolutionOutlined,
  StarOutlined,
  SyncOutlined,
  TableOutlined,
  TagOutlined,
  TeamOutlined,
  ToolOutlined,
  TrophyOutlined,
  UserOutlined,
  VerifiedOutlined,
  VideoCameraOutlined,
  WalletOutlined,
  WifiOutlined,
} from '@ant-design/icons';

export type IconProp = [string, React.FC];

export default new Map([
  // 数据类
  ['AreaChart', AreaChartOutlined],
  ['PieChart', PieChartOutlined],
  ['BarChart', BarChartOutlined],
  ['DotChart', DotChartOutlined],
  ['LineChart', LineChartOutlined],
  ['RadarChart', RadarChartOutlined],
  ['HeatMap', HeatMapOutlined],
  ['Fund', FundOutlined],
  ['Sliders', SlidersOutlined],

  // 品牌标识
  ['Android', AndroidOutlined],
  ['Apple', AppleOutlined],
  ['Windows', WindowsOutlined],
  ['Chrome', ChromeOutlined],
  ['Github', GithubOutlined],
  ['CodeSandbox', CodeSandboxOutlined],

  // 其他
  ['AccountBook', AccountBookOutlined],
  ['Apartment', ApartmentOutlined],
  ['Api', ApiOutlined],
  ['Appstore', AppstoreOutlined],
  ['Audit', AuditOutlined],
  ['Bank', BankOutlined],
  ['Bars', BarsOutlined],
  ['Book', BookOutlined],
  ['Bug', BugOutlined],
  ['Build', BuildOutlined],
  ['Calendar', CalendarOutlined],
  ['Ci', CiOutlined],
  ['Clear', ClearOutlined],
  ['CloudDownload', CloudDownloadOutlined],
  ['Cloud', CloudOutlined],
  ['Cluster', ClusterOutlined],
  ['Code', CodeOutlined],
  ['Comment', CommentOutlined],
  ['Compass', CompassOutlined],
  ['ConsoleSql', ConsoleSqlOutlined],
  ['Contacts', ContactsOutlined],
  ['Control', ControlOutlined],
  ['CreditCard', CreditCardOutlined],
  ['Crown', CrownOutlined],
  ['Dashboard', DashboardOutlined],
  ['Database', DatabaseOutlined],
  ['DeploymentUnit', DeploymentUnitOutlined],
  ['Desktop', DesktopOutlined],
  ['Download', DownloadOutlined],
  ['Environment', EnvironmentOutlined],
  ['Experiment', ExperimentOutlined],
  ['Fire', FireOutlined],
  ['Flag', FlagOutlined],
  ['Gift', GiftOutlined],
  ['Global', GlobalOutlined],
  ['History', HistoryOutlined],
  ['Home', HomeOutlined],
  ['Idcard', IdcardOutlined],
  ['Inbox', InboxOutlined],
  ['Insurance', InsuranceOutlined],
  ['Key', KeyOutlined],
  ['Mail', MailOutlined],
  ['Menu', MenuOutlined],
  ['MedicineBox', MedicineBoxOutlined],
  ['MoneyCollect', MoneyCollectOutlined],
  ['Picture', PictureOutlined],
  ['Profile', ProfileOutlined],
  ['Qrcode', QrcodeOutlined],
  ['Read', ReadOutlined],
  ['Robot', RobotOutlined],
  ['Safety', SafetyOutlined],
  ['Schedule', ScheduleOutlined],
  ['Search', SearchOutlined],
  ['Send', SendOutlined],
  ['Setting', SettingOutlined],
  ['ShareAlt', ShareAltOutlined],
  ['Shop', ShopOutlined],
  ['ShoppingCart', ShoppingCartOutlined],
  ['Shopping', ShoppingOutlined],
  ['Skin', SkinOutlined],
  ['Solution', SolutionOutlined],
  ['Star', StarOutlined],
  ['Sync', SyncOutlined],
  ['Table', TableOutlined],
  ['Tag', TagOutlined],
  ['Team', TeamOutlined],
  ['Tool', ToolOutlined],
  ['Trophy', TrophyOutlined],
  ['User', UserOutlined],
  ['Verified', VerifiedOutlined],
  ['VideoCamera', VideoCameraOutlined],
  ['Wallet', WalletOutlined],
  ['Wifi', WifiOutlined],
]);
